// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActiveLinkController from "./active_link_controller"
application.register("active-link", ActiveLinkController)

import Admin__ChartsController from "./admin/charts_controller"
application.register("admin--charts", Admin__ChartsController)

import AiCoachController from "./ai_coach_controller"
application.register("ai-coach", AiCoachController)

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import MultiStepFormController from "./multi_step_form_controller"
application.register("multi-step-form", MultiStepFormController)

import OverlayController from "./overlay_controller"
application.register("overlay", OverlayController)

import ProgramChatController from "./program_chat_controller"
application.register("program-chat", ProgramChatController)

import ScrollIndicatorController from "./scroll_indicator_controller"
application.register("scroll-indicator", ScrollIndicatorController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import VoiceRecorderController from "./voice_recorder_controller"
application.register("voice-recorder", VoiceRecorderController)
